create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    telegram_chat_id text,
    email text,
    institution text,
    student_id text,
    major text,
    password_hash text
);

create unique index if not exists idx_users_email
    on public.users (email) where email is not null;

create table if not exists public.deadlines (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete cascade,
    tugas_name text not null,
    deadline_date text not null,
    status text default 'pending',
    timezone text not null default 'Asia/Jakarta'
);

create table if not exists public.summaries (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete cascade,
    filename text not null,
    action_type text not null,
    result_text text not null,
    created_at timestamptz default now()
);

create table if not exists public.deadline_notifications (
    id bigint generated by default as identity primary key,
    deadline_id bigint not null references public.deadlines(id) on delete cascade,
    reminder_type text not null,
    sent_at timestamptz default now(),
    unique (deadline_id, reminder_type)
);

create table if not exists public.schedules (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    filename text not null,
    schedule_text text not null,
    created_at timestamptz default now()
);

create table if not exists public.schedule_entries (
    id bigint generated by default as identity primary key,
    schedule_id bigint not null references public.schedules(id) on delete cascade,
    day_name text not null,
    start_time text not null,
    end_time text not null,
    course_name text not null,
    room text,
    lecturer text,
    class_name text
);